name: medication_manager
description: A Flutter application implementing the medication management mockup.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  provider: ^6.1.2
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  url_launcher: ^6.2.5
  http: ^1.2.2
  google_maps_flutter: ^2.7.0
  image_picker: ^1.2.0
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_barcode_scanning: ^0.14.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
